services:
  - type: web
    name: tc_app
    env: docker
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: tcpg
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: TAB_DIRECTOR_EMAIL
        sync: false
      - key: TIME_ZONE
        sync: false
  - type: pserv
    name: tc_redis
    env: docker
    repo: https://github.com/render-examples/redis.git # optional
    envVars:
      - key: GENERATED_SECRET
        generateValue: true # will generate a base64-encoded 256-bit secret
      - key: DASHBOARD_SECRET
        sync: false # placeholder for a value to be added in the dashboard
    disk:
      name: redis-data
      mountPath: /var/lib/redis
      sizeGB: 10 # optional

databases:
  - name: tc_database
    databaseName: tabbycat
    user: tabbycat
    plan: free
