services:
  - type: web
    name: tabbycat
    env: python
    plan: free
    buildCommand: "./bin/render_compile.sh"
    startCommand: "gunicorn wsgi:application --config './config/gunicorn.conf'"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: tabbycat
          property: connectionString
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4

databases:
  - name: tabbycat
    databaseName: tabbycat
    user: tabbycat
    plan: free
