services:
  - type: web
    name: tc_app
    env: docker
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: tc_database
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: TAB_DIRECTOR_EMAIL
        sync: false
      - key: TIME_ZONE
        sync: false

databases:
  - name: tc_database
    databaseName: tabbycat
    user: tabbycat
    plan: free
